name: Pre-release

on:
  workflow_dispatch:

concurrency:
  group: pre-release-${{ github.repository }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/docker-build-push.yml
    permissions:
      contents: read
      packages: write
    with:
      tags: "ghcr.io/${{ github.repository }}:dev"
      nzbdav_version: pre-${{ github.run_number }}
    secrets:
      registry_token: ${{ secrets.GITHUB_TOKEN }}

  tag-dev:
    needs: build
    uses: ./.github/workflows/move-dev-tag.yml
    permissions:
      contents: write
    with:
      ref: ${{ github.sha }}
